// <auto-generated />
using System;
using Consommation.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Consommation.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241021135018_Ajustements")]
    partial class Ajustements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Consommation.Models.Commentaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Commentaires");
                });

            modelBuilder.Entity("Consommation.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Consommation.Models.Recharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CommentaireId")
                        .HasColumnType("int");

                    b.Property<int>("Coût")
                        .HasColumnType("int");

                    b.Property<int>("Durée")
                        .HasColumnType("int");

                    b.Property<int>("KwChargé")
                        .HasColumnType("int");

                    b.Property<int>("PrixKwh")
                        .HasColumnType("int");

                    b.Property<int>("PuChargéKwH")
                        .HasColumnType("int");

                    b.Property<int>("RatioBatterie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentaireId");

                    b.ToTable("Recharges");
                });

            modelBuilder.Entity("Consommation.Models.Trajet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CommentaireId")
                        .HasColumnType("int");

                    b.Property<int?>("ConsoClim")
                        .HasColumnType("int");

                    b.Property<int>("ConsoCumul")
                        .HasColumnType("int");

                    b.Property<int>("ConsoMoy100")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("EnergieRecup")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VitesseMoy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentaireId");

                    b.ToTable("Trajets");
                });

            modelBuilder.Entity("Consommation.Models.Voiture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Autonomie")
                        .HasColumnType("int");

                    b.Property<int>("ChargeBatterie")
                        .HasColumnType("int");

                    b.Property<int>("DistanceCumul")
                        .HasColumnType("int");

                    b.Property<int>("DistanceTot")
                        .HasColumnType("int");

                    b.Property<bool>("Reset")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Voitures");
                });

            modelBuilder.Entity("Consommation.Models.Recharge", b =>
                {
                    b.HasOne("Consommation.Models.Commentaire", "Commentaire")
                        .WithMany()
                        .HasForeignKey("CommentaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commentaire");
                });

            modelBuilder.Entity("Consommation.Models.Trajet", b =>
                {
                    b.HasOne("Consommation.Models.Commentaire", "Commentaire")
                        .WithMany()
                        .HasForeignKey("CommentaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commentaire");
                });
#pragma warning restore 612, 618
        }
    }
}
